<h1 align=center style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
    توابع تجمیعی
</font>
</h1>

In [1]:
import numpy as np
np.random.seed(1400)

In [2]:
a = np.random.randint(0, 10, 20)
print(a)
print('sum =', np.sum(a))
print('min =', np.min(a))
print('max =', np.max(a))

[5 1 7 8 5 8 1 8 3 8 9 8 4 1 4 4 1 7 3 1]
sum = 96
min = 1
max = 9


In [3]:
print(a.min(), a.max(), a.sum())

1 9 96


In [4]:
big_array = np.random.rand(1000*1000)
%timeit sum(big_array)
%timeit np.sum(big_array)

119 ms ± 23.7 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
454 µs ± 8.79 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [5]:
a = np.random.randint(0, 10, (3, 4))
print(a)

[[6 5 4 2]
 [0 1 4 5]
 [0 3 1 9]]


In [6]:
a.sum()

40

In [7]:
a.min(axis=0)

array([0, 1, 1, 2])

In [8]:
a.max(axis=1)

array([6, 5, 9])

In [9]:
heights = np.array([[194, 185, 183, 184, 178, 178, 190, 187, 187, 179, 186], 
                    [192, 173, 194, 184, 170, 189, 170, 170, 176, 173, 185]])
print('Iran vs Spain')
print('Mean height:', heights.mean(axis=1))
print('Standard deviation:', heights.std(axis=1))

Iran vs Spain
Mean height: [184.63636364 179.63636364]
Standard deviation: [4.79152144 8.91650897]


In [10]:
print('Min:', np.min(heights, axis=1)) 
print('25th percentile:', np.percentile(heights, 25, axis=1)) 
print('Median:', np.median(heights, axis=1))
print('75th percentile:', np.percentile(heights, 75, axis=1))
print('Max:', np.max(heights, axis=1))

Min: [178 170]
25th percentile: [181.  171.5]
Median: [185. 176.]
75th percentile: [187. 187.]
Max: [194 194]


In [11]:
b = np.array([8,3,5,9,2,6,4])
np.argmax(b)

3

In [12]:
np.argmin(b)

4