<h1 align=center style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
    مرتب‌سازی و جبر خطی
</font>
</h1>

In [1]:
import numpy as np
np.random.seed(1400)

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
مرتب‌سازی
</font>
</h2>
<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    یکی از پایه‌ای ترین مسئله‌های الگوریتمی در علوم کامپیوتر، مسئله مرتب‌سازی یک آرایه از اعداد است. برای این مسئله، الگوریتم‌های جالب و متعددی ارائه شده‌است. برای مثال، کد الگوریتم مرتب‌سازی درجی (insertion sort) در ادامه آمده‌است. در این الگوریتم پس از مرتب کردن عناصر قبل از عنصر i ام، این عنصر تا جایی که کوچکتر از عنصر قبلی خود باشد با آن جابجا می‌شود و به این ترتیب در جای مناسب خود درج می‌شود.
</font>
</p>

In [2]:
def insertion_sort(a):
    for i in range(len(a)):
        j = i
        while j > 0 and a[j] < a[j-1]:
            a[j], a[j-1] = a[j-1], a[j]
            j -= 1         

In [3]:
a = np.array([7, 3, 11, 13, 5])
insertion_sort(a)
print(a)

[ 3  5  7 11 13]


<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    الگوریتم‌های سریع‌تری چون مرتب‌سازی سریع (quick sort) در توابع آماده <code>sort</code> پایتون و نامپای پیاده‌سازی شده‌اند.
    <br>
    مرتبه زمانی این الگوریتم‌ها از O(nlogn) است.
    <br>
    به این ترتیب، برای مرتب‌سازی آرایه‌های نامپای از تابع <code>np.sort</code> استفاده می‌کنیم که آرایه را به صورت مرتب خروجی می‌دهد.
</font>
</p>

In [4]:
a = np.array([5, 2, 9, 4, 1])
np.sort(a)

array([1, 2, 4, 5, 9])

In [5]:
a.sort()
print(a)

[1 2 4 5 9]


<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    از قابلیت‌های دیگر این تابع در نامپای، مرتب‌سازی در راستای محوریست که با <code>axis</code> مشخص می‌شود.    
</font>
</p>

In [6]:
a = np.random.randint(0, 10, (4, 5))
print(a)

[[5 1 7 8 5]
 [8 1 8 3 8]
 [9 8 4 1 4]
 [4 1 7 3 1]]


In [7]:
np.sort(a, axis=0)

array([[4, 1, 4, 1, 1],
       [5, 1, 7, 3, 4],
       [8, 1, 7, 3, 5],
       [9, 8, 8, 8, 8]])

In [8]:
np.sort(a, axis=1)

array([[1, 5, 5, 7, 8],
       [1, 3, 8, 8, 8],
       [1, 4, 4, 8, 9],
       [1, 1, 3, 4, 7]])

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    در اینجا می‌توان به دو تابع مرتبط با مرتب‌سازی در نامپای هم اشاره کرد. تابع <code>np.partition</code> با ورودی گرفتن مقدار k ، آرایه‌ای را خروجی می‌دهد که در آن، k+1 عنصرِ کوچک‌ترِ آرایه، پیش از سایر عناصر آمده‌اند. هم‌چنین تابع <code>np.argsort</code> به جای آرایه مرتب شده، آرایه‌ای بر می‌گرداند که در خانه iم، آن شماره خانه iمین کوچک‌ترین عنصر آرایه قرار دارد.
</font>
</p>

In [9]:
np.partition(a, 2, axis=1)

array([[1, 5, 5, 8, 7],
       [1, 3, 8, 8, 8],
       [1, 4, 4, 9, 8],
       [1, 1, 3, 7, 4]])

In [10]:
a = np.array([5, 2, 7, 3, 1])
ind = np.argsort(a)
print(ind)

[4 1 3 0 2]


In [11]:
def my_sort(a):
    if len(a) == 1:
        return
    mid = len(a)//2
    a.partition(mid)
    my_sort(a[:mid])
    my_sort(a[mid:])

In [12]:
a = np.array([3, 5, 1, 4, 2])
my_sort(a)
print(a)

[1 2 3 4 5]


<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
جبرخطی
</font>
</h2>
<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    انجام عملیات‌ عنصر به عنصر، مانند جمع دو ماتریس، با استفاده از توابع عمومی‌ای که پیش از این آموختیم، امکان‌پذیر است. ضرب ماتریسی از اعمال متفاوتی است که برای انجام آن می‌توانیم از توابع <code>np.matmul</code> و <code>np.dot</code> استفاده کنیم. این توابع اگر دو آرایه یک بعدی هم‌اندازه ورودی بگیرند با آن‌ها مثل بردار برخورد می‌کنند و ضرب داخلیشان را در قالب یک عدد خروجی می‌دهند؛ اگر یکی از آرایه‌ها یک بعدی و دیگری دو بعدی باشد، خروجی یک آرایه‌ یک بعدیست که نشان دهنده ضرب بردار و ماتریس متناظر ورودی‌هاست؛ اگر هر دو ورودی دو بعدی باشند، خروجی آرایه دوبعدی‌ای خواهد بود که ماتریس حاصل‌ضرب را نشان می‌دهد (تفاوت کارکرد دو تابع در ازای ورودیِ عدد یا آرایه‌های با ابعاد بالاتر است). نمونه استفاده از آن‌ها را در کدهای زیر مشاهده می‌کنید.
</font>
</p>

In [13]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
print('x =', x)
print('y =', y)

x = [1 2 3]
y = [4 5 6]


In [14]:
np.matmul(x, y)

32

In [15]:
a = np.random.randint(1, 10, (3, 2))
b = np.random.randint(1, 10, (2, 3))
print(a)
print(b)

[[4 8]
 [5 4]
 [1 3]]
[[8 9 9]
 [7 1 4]]


In [16]:
np.matmul(x, a)

array([17, 25])

In [17]:
np.matmul(b, x)

array([53, 21])

In [18]:
np.matmul(a, b)

array([[88, 44, 68],
       [68, 49, 61],
       [29, 12, 21]])

In [19]:
print(x @ y)
print(a.dot(b))

32
[[88 44 68]
 [68 49 61]
 [29 12 21]]


<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
انجام عملیات‌ جبرخطی روی ماتریس‌ها که با آرایه‌های یک بعدی و دوبعدی نشان داده می‌شوند، به اندازه‌ای کاربردی است که یک زیربخش به نام <code>linalg</code> در نامپای برای گردآوری آن‌ها اختصاص داده شده‌است. برای مثال دو تابع <code>det</code> و <code>inv</code> به ترتیب دترمینان و ماتریس معکوس یک ماتریس مربعی را محاسبه می‌کنند.
</font>
</p>

In [20]:
from numpy.linalg import inv, det
a = np.random.randn(4, 4)
print(a)

[[ 0.287707    0.72095045  2.54237031  1.21466404]
 [-0.45681235 -0.94863596 -0.65169317  1.08989865]
 [ 0.79223134 -0.32689059 -0.52634427 -0.32662089]
 [-2.33822523 -1.77578789  0.05496365  2.50592755]]


In [21]:
det(a)

-2.599943720778108

In [22]:
inv(a)

array([[ 0.27535742,  0.56235807,  0.60248102, -0.29952868],
       [ 0.03712256,  1.89311229, -2.28358677, -1.13900305],
       [ 0.21861554, -1.5079133 ,  1.09542126,  0.69264401],
       [ 0.27844123,  1.89932312, -1.08009419, -0.70275918]])