<h1 align=center style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
تعریف آرایه
    </font>
</h1>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
ابتدا کد زیر را اجرا کنید تا ضمن اطمینان از نصب موفقیت آمیز نامپای از نسخه نصب شده مطلع شوید.
    </font>
</p>

In [2]:
import numpy as np # عموما به طور قراردادی از کتابخانهٔ نامپای به این شکل استفاده می‌شود
np.__version__ 

'1.26.4'

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
در این دوره از نسخه 1.21.0 نامپای استفاده شده است و خروجی‌هایی که خواهید دید، با این نسخه تولید شده است.
    </font>
</p>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
ساخت آرایه🔗
    </font>
</h2>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    یکی از راه‌های ساخت آرایه نامپای ورودی دادن لیست پایتون به تابع <code>array</code> نامپای است.
    در کدهای زیر نمونه‌هایی از این نوع ایجاد آرایه را می‌بینید.
</font>
</p>

In [2]:
np.array([1, 2, 3]) # آرایه یک بعدی شامل 3 عدد

array([1, 2, 3])

In [3]:
np.array([[1, 2], # آرایه دو بعدی 2*3 شامل 6 عدد 
         [3, 4],
         [5, 6]])

array([[1, 2],
       [3, 4],
       [5, 6]])

In [4]:
np.array([[['000', '001'], ['010', '011']], # آرایه سه بعدی 2*2*2 شامل 8 رشته
          [['100', '101'], ['110', '111']]])
# نوع خانه‌های آرایه را نشان می‌دهد و dtype
# که نوع این آرایه می‌شود به معنای رشته یونی‌کد 3 حرفی است <U3

array([[['000', '001'],
        ['010', '011']],

       [['100', '101'],
        ['110', '111']]], dtype='<U3')

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
یک راه دیگر برای ساخت آراه نامپای، استفاده از توابع داخلی نامپای است که چند نمونه از آن را در کدهای زیر می‌بینید.
    </font>
</p>

In [5]:
np.zeros(3) # آرایه یک بعدی شامل 3 عدد حقیقی برابر صفر

array([0., 0., 0.])

In [6]:
np.ones((2, 3)) # آرایه دو بعدی 3*2 شامل 6 عدد حقیقی برابر یک

array([[1., 1., 1.],
       [1., 1., 1.]])

In [7]:
np.full((3, 2), '#') # آرایه دو بعدی 2*3 شامل 6 رشتهٔ '#' یکسان

array([['#', '#'],
       ['#', '#'],
       ['#', '#']], dtype='<U1')

In [8]:
np.arange(0, 15, 4) # آرایه یک بعدی شامل اعداد صحیح پیش از 15 با شروع از 0 و با فاصله 4

array([ 0,  4,  8, 12])

In [9]:
np.linspace(0, 20, 5) # آرایه یک بعدی شامل 5 عدد حقیقی در بازه 0 تا 20 (شامل این دو) با فاصله برابر

array([ 0.,  5., 10., 15., 20.])

In [10]:
np.eye(3) # آرایه دو بعدی 3*3 متناظر با ماتریس همانی (قطر 1 و باقی خانه‌ها 0)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
np.empty(3) # آرایه یک بعدی شامل 3 عدد نامشخص (بسته به مقدار داخل حافظه)

array([1., 1., 1.])

In [12]:
np.random.random(3) # آرایه یک بعدی شامل 3 عدد تصادفی از توزیع یکنواخت بین 0 و 1

array([0.39854015, 0.8626059 , 0.3290462 ])

In [13]:
np.random.randint(0, 10, (3, 3)) # آرایه دو بعدی 3*3 شامل اعداد صحیح تصادفی بین 0 تا 9 

array([[7, 9, 0],
       [5, 1, 6],
       [0, 2, 1]])

In [14]:
np.random.normal(0, 1, (2, 3)) # آرایه دو بعدی 3*2 شامل اعداد تصادفی از توزیع نرمال با میانگین 0 و واریانس 1 

array([[ 0.69357759,  1.37739676, -0.38610756],
       [-0.02693393, -0.98392048, -0.50565211]])

In [15]:
a = np.random.randint(0, 10, (2, 3))
np.full_like(a, 3) # آرایه پر از 3 با ابعاد مشابه آرایه ورودی (3*2)

array([[3, 3, 3],
       [3, 3, 3]])

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
نوع داده🔗
    </font>
</h2>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    در کدهای زیر، چگونگی تعیین نوع داده آرایه با تعیین <code>dtype</code> هنگام ساخت را می‌بینید.    </font>
</p>

In [16]:
np.array([False, True], dtype='bool_') # نوع مقدار بولی
# کاراکتر _ برای اشاره به نوع داخل نامپای است اما می‌توان آن را برداشت

array([False,  True])

In [17]:
np.array([1, 2, 3.14], dtype='int_') # نوع عدد صحیح (عدد سوم تبدیل به 3 می‌شود)

array([1, 2, 3])

In [18]:
np.array([2.71828182845, 3.14159265359], dtype='float128') # نوع عدد حقیقی 128 بیتی

array([2.71828183, 3.14159265], dtype=float128)

In [19]:
np.array([255], dtype='uint8') # نوع عدد صحیح نامنفی 8 بیتی

array([255], dtype=uint8)

In [20]:
np.array(['Hello', 'World'], dtype='str_') # نوع رشته

array(['Hello', 'World'], dtype='<U5')

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
مشخصه‌ها
    </font>
</h2>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
در کدهای زیر، چند مثال از مشخصه‌های آرایه را مشاهده می‌کنید.
</p>

In [21]:
a = np.array([[1, 2],
             [3, 4],
             [5, 6]], dtype='float64')
print(a)
print('number of dimensions:', a.ndim) # تعداد ابعاد آرایه
print('shape:', a.shape) # اندازه ابعاد آرایه
print('size:', a.size) # تعداد خانه‌های آرایه
print('dtype:', a.dtype) # نوع داده آرایه

[[1. 2.]
 [3. 4.]
 [5. 6.]]
number of dimensions: 2
shape: (3, 2)
size: 6
dtype: float64


In [22]:
c = np.array(['h', 'e', 'l', 'l', 'o'])
print(c)
print(c.itemsize, 'bytes') # تعداد بایت برای هر خانه آرایه
print(c.nbytes, 'bytes') # تعداد بایت برای کل آرایه

['h' 'e' 'l' 'l' 'o']
4 bytes
20 bytes
