# Numpy

- Numpy is Numerical Python !
  
- As you can see the python list save objects inside itself but the numpy array and all its belongings are whole an object!

    <img src="https://devopedia.org/images/article/251/4000.1588007216.png" alt="..." style="width:700px;"/>


In [26]:
import numpy as np

In [27]:
my_array = np.array([1,2,3])

In [28]:
type(my_array)

numpy.ndarray

In [29]:
my_array.ndim

1

In [35]:
my_array.shape

(3, 2)

In [87]:
my_array.nbytes

8

In [86]:
my_array.itemsize

8

In [34]:
my_array = np.array([
    [1,2],
    [3,4],
    [5,6]
])

In [32]:
my_array.ndim

2

In [33]:
my_array.shape

(3, 2)

In [41]:
my_array = np.array(12)
my_array.ndim

0

In [36]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [39]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [51]:
np.ones((3,5,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [56]:
np.full((5,6), fill_value='#')

array([['#', '#', '#', '#', '#', '#'],
       ['#', '#', '#', '#', '#', '#'],
       ['#', '#', '#', '#', '#', '#'],
       ['#', '#', '#', '#', '#', '#'],
       ['#', '#', '#', '#', '#', '#']], dtype='<U1')

In [60]:
np.arange(23, 455,6)

array([ 23,  29,  35,  41,  47,  53,  59,  65,  71,  77,  83,  89,  95,
       101, 107, 113, 119, 125, 131, 137, 143, 149, 155, 161, 167, 173,
       179, 185, 191, 197, 203, 209, 215, 221, 227, 233, 239, 245, 251,
       257, 263, 269, 275, 281, 287, 293, 299, 305, 311, 317, 323, 329,
       335, 341, 347, 353, 359, 365, 371, 377, 383, 389, 395, 401, 407,
       413, 419, 425, 431, 437, 443, 449])

In [61]:
np.arange(0, 10,2, dtype=np.uint8)

array([0, 2, 4, 6, 8], dtype=uint8)

In [67]:
np.linspace(0,155,3)

array([  0. ,  77.5, 155. ])

In [68]:
np.linspace(0,155,3, dtype=np.uint8)

array([  0,  77, 155], dtype=uint8)

In [70]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [85]:
np.empty((3,5), dtype=np.bool_)

array([[ True,  True,  True,  True,  True],
       [False, False, False, False, False],
       [False, False, False, False, False]])