# Numpy

- Numpy is Numerical Python !
  
- As you can see the python list save objects inside itself but the numpy array and all its belongings are whole an object!

    <img src="https://devopedia.org/images/article/251/4000.1588007216.png" alt="..." style="width:700px;"/>

- Dimensions in numpy arrays:
    
    <img src="https://nustat.github.io/DataScience_Intro_python/Datasets/numpy_image.png" alt="..." style="width:700px;">


In [6]:
import numpy as np

In [2]:
my_array = np.array([1,2,3])

In [3]:
type(my_array)

numpy.ndarray

In [4]:
my_array.ndim

1

In [5]:
my_array.shape

(3,)

In [6]:
print(my_array)
print('each item:', my_array.itemsize, 'bytes')
print('total:',my_array.nbytes, 'bytes')

[1 2 3]
each item: 8 bytes
total: 24 bytes


In [7]:
my_array = np.array([
    [1,2],
    [3,4],
    [5,6]
])

In [8]:
my_array.ndim

2

In [9]:
my_array.shape

(3, 2)

In [10]:
my_array = np.array(12)
my_array.ndim

0

In [11]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
np.ones((3,5,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [14]:
np.full((5,6), fill_value='#')

array([['#', '#', '#', '#', '#', '#'],
       ['#', '#', '#', '#', '#', '#'],
       ['#', '#', '#', '#', '#', '#'],
       ['#', '#', '#', '#', '#', '#'],
       ['#', '#', '#', '#', '#', '#']], dtype='<U1')

In [15]:
np.arange(23, 455,6)

array([ 23,  29,  35,  41,  47,  53,  59,  65,  71,  77,  83,  89,  95,
       101, 107, 113, 119, 125, 131, 137, 143, 149, 155, 161, 167, 173,
       179, 185, 191, 197, 203, 209, 215, 221, 227, 233, 239, 245, 251,
       257, 263, 269, 275, 281, 287, 293, 299, 305, 311, 317, 323, 329,
       335, 341, 347, 353, 359, 365, 371, 377, 383, 389, 395, 401, 407,
       413, 419, 425, 431, 437, 443, 449])

In [16]:
np.arange(0, 10,2, dtype=np.uint8)

array([0, 2, 4, 6, 8], dtype=uint8)

In [17]:
np.linspace(0,155,3)

array([  0. ,  77.5, 155. ])

In [18]:
np.linspace(0,155,3, dtype=np.uint8)

array([  0,  77, 155], dtype=uint8)

In [19]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [20]:
np.empty((3,5), dtype=np.bool_)

array([[ True,  True,  True,  True,  True],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [21]:
hello = np.array(['h','e','l','l','o'])
print('each item:', hello.itemsize, 'bytes')
print('total:',hello.nbytes, 'bytes')

each item: 4 bytes
total: 20 bytes


In [22]:
np.random.random(size=(4,3))

array([[0.71638   , 0.187523  , 0.05532264],
       [0.05711507, 0.02345762, 0.75895563],
       [0.19612521, 0.99219119, 0.73595274],
       [0.09957322, 0.91871671, 0.8383386 ]])

In [23]:
np.random.randint(10,20,(2,4,5), dtype=np.uint8)

array([[[18, 11, 18, 15, 16],
        [11, 10, 17, 12, 19],
        [11, 18, 11, 17, 13],
        [15, 18, 19, 16, 15]],

       [[16, 14, 17, 11, 15],
        [15, 12, 11, 17, 12],
        [18, 16, 11, 11, 13],
        [10, 19, 19, 16, 15]]], dtype=uint8)

In [24]:
np.random.normal(10,20,(3,4,2))

array([[[ 1.13329502e+01,  3.65733937e+01],
        [ 5.04688419e+01, -1.62323749e+01],
        [ 3.51537818e+01,  1.27294417e+01],
        [-2.04640503e+01,  3.45190485e+01]],

       [[ 2.29281090e+01,  3.60270347e-02],
        [ 3.87401349e+01,  7.84017112e+00],
        [ 6.10650834e+00,  1.01283806e+01],
        [ 3.00938107e+01,  2.64426400e+00]],

       [[ 1.66377238e+01,  4.25785338e+00],
        [-4.18297150e+00,  2.27543114e+01],
        [-1.92540379e+01,  3.58275675e+01],
        [ 1.29022301e+01,  4.88541428e+01]]])

In [25]:
my_array = np.random.randint(0,10,(2,4,3))
my_array

array([[[7, 3, 5],
        [0, 7, 9],
        [8, 1, 6],
        [5, 5, 8]],

       [[3, 5, 8],
        [4, 3, 4],
        [6, 1, 8],
        [5, 7, 0]]])

In [26]:
np.full_like(my_array, 3)

array([[[3, 3, 3],
        [3, 3, 3],
        [3, 3, 3],
        [3, 3, 3]],

       [[3, 3, 3],
        [3, 3, 3],
        [3, 3, 3],
        [3, 3, 3]]])

In [27]:
my_array[1,1,2]

4

In [28]:
a = np.array([[0, 1, 2],
              [3, 4, 5],
              [6, 7, 8]])
print('a:\n', a)
sub_a = a[1:3, 1:]
print('sub a:\n',sub_a)
sub_a[0, 0] = 10
print('sub a:\n', sub_a)
print('a:\n',a)

a:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
sub a:
 [[4 5]
 [7 8]]
sub a:
 [[10  5]
 [ 7  8]]
a:
 [[ 0  1  2]
 [ 3 10  5]
 [ 6  7  8]]


In [29]:
a = np.array([[0, 1, 2],
              [3, 4, 5],
              [6, 7, 8]])
print("a:\n", a)
sub_copy_a = a[2:4, 1:].copy()
print("sub a:\n", sub_copy_a)
sub_copy_a[0, 0] = 10
print("sub a:\n", sub_copy_a)
print(a)

a:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
sub a:
 [[7 8]]
sub a:
 [[10  8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [30]:
before = np.linspace(0,29,16,dtype=np.uint8)
print("Before:\n", before)
after = before.reshape(4,4)
print("After:\n", after)


Before:
 [ 0  1  3  5  7  9 11 13 15 17 19 21 23 25 27 29]
After:
 [[ 0  1  3  5]
 [ 7  9 11 13]
 [15 17 19 21]
 [23 25 27 29]]


In [31]:
before = np.arange(1,10)
print("Before:\n", before)
after = before.reshape(3,3)
print("After:\n", after)

Before:
 [1 2 3 4 5 6 7 8 9]
After:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [32]:
before = np.arange(30)
print("Before:\n", before)
after = before.reshape(2,5,-1)
print("After:\n", after)

Before:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
After:
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]]


In [33]:
before = np.random.randint(low=0,high=2,size=(2,4,3))
print("Before:\n", before)
after = before.reshape(-1)
print("After:\n", after)

Before:
 [[[0 1 1]
  [0 0 1]
  [0 1 0]
  [1 0 0]]

 [[0 0 1]
  [1 0 0]
  [1 1 1]
  [0 1 1]]]
After:
 [0 1 1 0 0 1 0 1 0 1 0 0 0 0 1 1 0 0 1 1 1 0 1 1]


In [34]:

a = np.array([[0, 1, 2],
             [3, 4, 5],
             [6, 7, 8],
             [9, 10, 11]])
print(a.size)
print(a.shape)
print(a.ndim)
print(a[:2, 1:2])
print(a[:2, 1])

12
(4, 3)
2
[[1]
 [4]]
[1 4]


## Transpose
<img src="https://quera.org/qbox/view/xfWkJ9uk6z/transpose.gif" alt="...">

In [46]:
a = np.arange(6).reshape(2,3)
print(a,'\n')
print(a.T,'\n')
print(np.transpose(a),'\n')

[[0 1 2]
 [3 4 5]] 

[[0 3]
 [1 4]
 [2 5]] 

[[0 3]
 [1 4]
 [2 5]] 



In [67]:
a = np.arange(24).reshape(2, 3, 4)
print(a,'\n-----------')
print(a.transpose(1,2,0))

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]] 
-----------
[[[ 0 12]
  [ 1 13]
  [ 2 14]
  [ 3 15]]

 [[ 4 16]
  [ 5 17]
  [ 6 18]
  [ 7 19]]

 [[ 8 20]
  [ 9 21]
  [10 22]
  [11 23]]]


In [72]:
a = np.arange(24).reshape(3,4,2)
print(a,'\n-------')
print(a.swapaxes(0,1)) # zero dimension which is 3 / first dimension which is 4

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]] 
-------
[[[ 0  1]
  [ 8  9]
  [16 17]]

 [[ 2  3]
  [10 11]
  [18 19]]

 [[ 4  5]
  [12 13]
  [20 21]]

 [[ 6  7]
  [14 15]
  [22 23]]]


In [15]:
a = np.arange(24).reshape(3,4,2)
print(a)
print('-----------')
b = a.swapaxes(0,2)
print(b)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]]
-----------
[[[ 0  8 16]
  [ 2 10 18]
  [ 4 12 20]
  [ 6 14 22]]

 [[ 1  9 17]
  [ 3 11 19]
  [ 5 13 21]
  [ 7 15 23]]]


## Concatenate
<img src="https://quera.org/qbox/view/Yw0nPkHTuR/concatenate.gif">

In [26]:
a = np.arange(6).reshape(2,3)
b = np.arange(7,13).reshape(2,3)
print(np.concatenate((a,b)))
print("----------")
print(np.concatenate((a,b), axis=None))
print("----------")
print(np.concatenate((a,b), axis=1))
print("----------")
print(np.concatenate((a,b), axis=0))


[[ 0  1  2]
 [ 3  4  5]
 [ 7  8  9]
 [10 11 12]]
----------
[ 0  1  2  3  4  5  7  8  9 10 11 12]
----------
[[ 0  1  2  7  8  9]
 [ 3  4  5 10 11 12]]
----------
[[ 0  1  2]
 [ 3  4  5]
 [ 7  8  9]
 [10 11 12]]


## Split

<img src="https://quera.org/qbox/view/SHhG2Vh91J/split.png" alt="..." style="width:800px;">

In [21]:
a = np.arange(1,21)
np.split(a, [5,10,15])

[array([1, 2, 3, 4, 5]),
 array([ 6,  7,  8,  9, 10]),
 array([11, 12, 13, 14, 15]),
 array([16, 17, 18, 19, 20])]

In [47]:
a = np.arange(24).reshape(4,6)
b,c = np.split(a,2,axis=0)
d,e,f = np.split(a,3,axis=1)
print(b,'\n---------\n',c,'\n---------')
print(d,'\n---------\n',e,'\n---------\n',f)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]] 
---------
 [[12 13 14 15 16 17]
 [18 19 20 21 22 23]] 
---------
[[ 0  1]
 [ 6  7]
 [12 13]
 [18 19]] 
---------
 [[ 2  3]
 [ 8  9]
 [14 15]
 [20 21]] 
---------
 [[ 4  5]
 [10 11]
 [16 17]
 [22 23]]
