# Numpy

- Numpy is Numerical Python !
  
- As you can see the python list save objects inside itself but the numpy array and all its belongings are whole an object!

    <img src="https://devopedia.org/images/article/251/4000.1588007216.png" alt="..." style="width:700px;"/>

- Dimensions in numpy arrays:
    
    <img src="https://nustat.github.io/DataScience_Intro_python/Datasets/numpy_image.png" alt="..." style="width:700px;">


In [1]:
import numpy as np

In [2]:
my_array = np.array([1,2,3])

In [3]:
type(my_array)

numpy.ndarray

In [4]:
my_array.ndim

1

In [5]:
my_array.shape

(3,)

In [6]:
print(my_array)
print('each item:', my_array.itemsize, 'bytes')
print('total:',my_array.nbytes, 'bytes')

[1 2 3]
each item: 8 bytes
total: 24 bytes


In [7]:
my_array = np.array([
    [1,2],
    [3,4],
    [5,6]
])

In [8]:
my_array.ndim

2

In [9]:
my_array.shape

(3, 2)

In [10]:
my_array = np.array(12)
my_array.ndim

0

In [11]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
np.ones((3,5,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [14]:
np.full((5,6), fill_value='#')

array([['#', '#', '#', '#', '#', '#'],
       ['#', '#', '#', '#', '#', '#'],
       ['#', '#', '#', '#', '#', '#'],
       ['#', '#', '#', '#', '#', '#'],
       ['#', '#', '#', '#', '#', '#']], dtype='<U1')

In [15]:
np.arange(23, 455,6)

array([ 23,  29,  35,  41,  47,  53,  59,  65,  71,  77,  83,  89,  95,
       101, 107, 113, 119, 125, 131, 137, 143, 149, 155, 161, 167, 173,
       179, 185, 191, 197, 203, 209, 215, 221, 227, 233, 239, 245, 251,
       257, 263, 269, 275, 281, 287, 293, 299, 305, 311, 317, 323, 329,
       335, 341, 347, 353, 359, 365, 371, 377, 383, 389, 395, 401, 407,
       413, 419, 425, 431, 437, 443, 449])

In [16]:
np.arange(0, 10,2, dtype=np.uint8)

array([0, 2, 4, 6, 8], dtype=uint8)

In [17]:
np.linspace(0,155,3)

array([  0. ,  77.5, 155. ])

In [18]:
np.linspace(0,155,3, dtype=np.uint8)

array([  0,  77, 155], dtype=uint8)

In [19]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [20]:
np.empty((3,5), dtype=np.bool_)

array([[ True,  True,  True,  True,  True],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [21]:
hello = np.array(['h','e','l','l','o'])
print('each item:', hello.itemsize, 'bytes')
print('total:',hello.nbytes, 'bytes')

each item: 4 bytes
total: 20 bytes


In [22]:
np.random.random(size=(4,3))

array([[0.59558192, 0.2289994 , 0.00438629],
       [0.52524037, 0.08866197, 0.48378234],
       [0.2260851 , 0.75056939, 0.997196  ],
       [0.8576019 , 0.5606407 , 0.39325732]])

In [23]:
np.random.randint(10,20,(2,4,5), dtype=np.uint8)

array([[[18, 19, 17, 12, 18],
        [14, 13, 14, 15, 12],
        [13, 17, 17, 15, 15],
        [16, 19, 12, 13, 13]],

       [[16, 19, 10, 18, 12],
        [14, 16, 13, 16, 11],
        [16, 12, 18, 18, 11],
        [19, 19, 11, 14, 15]]], dtype=uint8)

In [24]:
np.random.normal(10,20,(3,4,2))

array([[[ 28.65866481, -15.69267419],
        [ 18.07876861,  27.6889657 ],
        [-12.66199965,  30.52256237],
        [  5.19786704,  21.4301482 ]],

       [[ 32.97413894,  11.25308355],
        [ -4.92390005,   1.96885154],
        [  6.96792282,   8.50240278],
        [-11.47282233,  10.91484316]],

       [[ -6.02009708,  16.72140105],
        [ 16.25590144, -23.50036609],
        [  8.09899023,  24.17153843],
        [  7.92847606,   1.31382803]]])

In [25]:
my_array = np.random.randint(0,10,(2,4,3))
my_array

array([[[8, 3, 2],
        [2, 9, 8],
        [8, 1, 4],
        [3, 6, 8]],

       [[0, 1, 5],
        [2, 3, 7],
        [3, 4, 2],
        [7, 6, 8]]])

In [26]:
np.full_like(my_array, 3)

array([[[3, 3, 3],
        [3, 3, 3],
        [3, 3, 3],
        [3, 3, 3]],

       [[3, 3, 3],
        [3, 3, 3],
        [3, 3, 3],
        [3, 3, 3]]])

In [27]:
my_array[1,1,2]

7

In [28]:
a = np.array([[0, 1, 2],
              [3, 4, 5],
              [6, 7, 8]])
print('a:\n', a)
sub_a = a[1:3, 1:]
print('sub a:\n',sub_a)
sub_a[0, 0] = 10
print('sub a:\n', sub_a)
print('a:\n',a)

a:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
sub a:
 [[4 5]
 [7 8]]
sub a:
 [[10  5]
 [ 7  8]]
a:
 [[ 0  1  2]
 [ 3 10  5]
 [ 6  7  8]]


In [29]:
a = np.array([[0, 1, 2],
              [3, 4, 5],
              [6, 7, 8]])
print("a:\n", a)
sub_copy_a = a[2:4, 1:].copy()
print("sub a:\n", sub_copy_a)
sub_copy_a[0, 0] = 10
print("sub a:\n", sub_copy_a)
print(a)

a:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
sub a:
 [[7 8]]
sub a:
 [[10  8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [30]:
before = np.linspace(0,29,16,dtype=np.uint8)
print("Before:\n", before)
after = before.reshape(4,4)
print("After:\n", after)


Before:
 [ 0  1  3  5  7  9 11 13 15 17 19 21 23 25 27 29]
After:
 [[ 0  1  3  5]
 [ 7  9 11 13]
 [15 17 19 21]
 [23 25 27 29]]


In [31]:
before = np.arange(1,10)
print("Before:\n", before)
after = before.reshape(3,3)
print("After:\n", after)

Before:
 [1 2 3 4 5 6 7 8 9]
After:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [32]:
before = np.arange(30)
print("Before:\n", before)
after = before.reshape(2,5,-1)
print("After:\n", after)

Before:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
After:
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]]


In [33]:
before = np.random.randint(low=0,high=2,size=(2,4,3))
print("Before:\n", before)
after = before.reshape(-1)
print("After:\n", after)

Before:
 [[[0 0 0]
  [0 0 0]
  [0 1 1]
  [0 0 0]]

 [[0 1 1]
  [0 0 1]
  [1 0 1]
  [0 1 1]]]
After:
 [0 0 0 0 0 0 0 1 1 0 0 0 0 1 1 0 0 1 1 0 1 0 1 1]


In [34]:

a = np.array([[0, 1, 2],
             [3, 4, 5],
             [6, 7, 8],
             [9, 10, 11]])
print(a.size)
print(a.shape)
print(a.ndim)
print(a[:2, 1:2])
print(a[:2, 1])

12
(4, 3)
2
[[1]
 [4]]
[1 4]


## Transpose
<img src="https://quera.org/qbox/view/xfWkJ9uk6z/transpose.gif" alt="...">

In [35]:
a = np.arange(6).reshape(2,3)
print(a,'\n')
print(a.T,'\n')
print(np.transpose(a),'\n')

[[0 1 2]
 [3 4 5]] 

[[0 3]
 [1 4]
 [2 5]] 

[[0 3]
 [1 4]
 [2 5]] 



In [36]:
a = np.arange(24).reshape(2, 3, 4)
print(a,'\n-----------')
print(a.transpose(1,2,0))

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]] 
-----------
[[[ 0 12]
  [ 1 13]
  [ 2 14]
  [ 3 15]]

 [[ 4 16]
  [ 5 17]
  [ 6 18]
  [ 7 19]]

 [[ 8 20]
  [ 9 21]
  [10 22]
  [11 23]]]


In [37]:
a = np.arange(24).reshape(3,4,2)
print(a,'\n-------')
print(a.swapaxes(0,1)) # zero dimension which is 3 / first dimension which is 4

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]] 
-------
[[[ 0  1]
  [ 8  9]
  [16 17]]

 [[ 2  3]
  [10 11]
  [18 19]]

 [[ 4  5]
  [12 13]
  [20 21]]

 [[ 6  7]
  [14 15]
  [22 23]]]


In [38]:
a = np.arange(24).reshape(3,4,2)
print(a)
print('-----------')
b = a.swapaxes(0,2)
print(b)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]]
-----------
[[[ 0  8 16]
  [ 2 10 18]
  [ 4 12 20]
  [ 6 14 22]]

 [[ 1  9 17]
  [ 3 11 19]
  [ 5 13 21]
  [ 7 15 23]]]


## Concatenate
<img src="https://quera.org/qbox/view/Yw0nPkHTuR/concatenate.gif">

In [39]:
a = np.arange(6).reshape(2,3)
b = np.arange(7,13).reshape(2,3)
print(np.concatenate((a,b)))
print("----------")
print(np.concatenate((a,b), axis=None))
print("----------")
print(np.concatenate((a,b), axis=1))
print("----------")
print(np.concatenate((a,b), axis=0))


[[ 0  1  2]
 [ 3  4  5]
 [ 7  8  9]
 [10 11 12]]
----------
[ 0  1  2  3  4  5  7  8  9 10 11 12]
----------
[[ 0  1  2  7  8  9]
 [ 3  4  5 10 11 12]]
----------
[[ 0  1  2]
 [ 3  4  5]
 [ 7  8  9]
 [10 11 12]]


## Split

<img src="https://quera.org/qbox/view/SHhG2Vh91J/split.png" alt="..." style="width:800px;">

In [40]:
a = np.arange(1,21)
np.split(a, [5,10,15])

[array([1, 2, 3, 4, 5]),
 array([ 6,  7,  8,  9, 10]),
 array([11, 12, 13, 14, 15]),
 array([16, 17, 18, 19, 20])]

In [41]:
a = np.arange(24).reshape(4,6)
b,c = np.split(a,2,axis=0)
d,e,f = np.split(a,3,axis=1)
print(b,'\n---------\n',c,'\n---------')
print(d,'\n---------\n',e,'\n---------\n',f)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]] 
---------
 [[12 13 14 15 16 17]
 [18 19 20 21 22 23]] 
---------
[[ 0  1]
 [ 6  7]
 [12 13]
 [18 19]] 
---------
 [[ 2  3]
 [ 8  9]
 [14 15]
 [20 21]] 
---------
 [[ 4  5]
 [10 11]
 [16 17]
 [22 23]]


In [42]:
a = np.random.randint(0, 10, (3,4))
b = np.random.randint(0, 10, (3,4)) 
print('a :\n', a)
print('b :\n', b)

def cal_sum(a, b) :
    output = np.empty(a.shape, dtype='int_')
    for i in range(len(a)):
        output[i] = a[i] + b[i]
    return output
print("SUM:")
print(cal_sum(a, b))

a :
 [[6 1 7 2]
 [1 2 5 2]
 [2 9 5 3]]
b :
 [[6 6 7 2]
 [5 3 8 0]
 [3 2 4 4]]
SUM:
[[12  7 14  4]
 [ 6  5 13  2]
 [ 5 11  9  7]]


## Binary Universal Functions

- #### add
  ```python
  np.add(a,b)
  ```
- #### subtract
    ```python
  np.subtract(a,b)
  ```
- #### multiply
    ```python
  np.multiply(a,b)
  ```
- #### divide
    ```python
  np.divide(a,b)
  ```

In [43]:
a = np.random.randint(0,11,(4,5))
b = np.random.randint(1,11,(4,5))
 
print(a)
print()
print(b)
print()
print(np.add(a,b),'\n--------------')
print(np.subtract(a,b),'\n------------')
print(np.multiply(a,b),'\n------------')
print(np.divide(a,b,dtype=np.float16))


[[4 3 5 4 6]
 [7 4 5 6 1]
 [8 6 1 0 4]
 [4 8 7 9 7]]

[[ 6  2  7  8 10]
 [ 2  7  5  6  9]
 [ 7 10  5  5  1]
 [ 1  6  6  1  5]]

[[10  5 12 12 16]
 [ 9 11 10 12 10]
 [15 16  6  5  5]
 [ 5 14 13 10 12]] 
--------------
[[-2  1 -2 -4 -4]
 [ 5 -3  0  0 -8]
 [ 1 -4 -4 -5  3]
 [ 3  2  1  8  2]] 
------------
[[24  6 35 32 60]
 [14 28 25 36  9]
 [56 60  5  0  4]
 [ 4 48 42  9 35]] 
------------
[[0.6665 1.5    0.7144 0.5    0.6   ]
 [3.5    0.5713 1.     1.     0.1111]
 [1.143  0.6    0.2    0.     4.    ]
 [4.     1.333  1.167  9.     1.4   ]]


## Unary Universal Functions

- #### abs
  ```python
  np.abs(a)
  ```
- #### sqrt
    ```python
  np.sqrt(a)
  ```
- #### square
    ```python
  np.square(a)
  ```
- #### isnan
    ```python
  np.isnan(a)
  ```

In [44]:
a = np.random.randint(-10,10,(3,3))
print(a)
print()
print(np.square(a),'\n--------------')
print(np.abs(a),'\n------------')
print(np.isnan(a),'\n------------')
np.seterr(invalid="ignore")
print(np.sqrt(a,dtype=np.float16))

[[ 0 -2 -6]
 [ 3  4 -5]
 [ 4  1 -4]]

[[ 0  4 36]
 [ 9 16 25]
 [16  1 16]] 
--------------
[[0 2 6]
 [3 4 5]
 [4 1 4]] 
------------
[[False False False]
 [False False False]
 [False False False]] 
------------
[[0.      nan   nan]
 [1.732 2.      nan]
 [2.    1.      nan]]


## Aggregation Functions

- #### sum
  ```python
  np.sum(a)
  a.sum()
  ```

- #### max
  ```python
  np.max(a)
  np.argmax(a)
  a.max()
  ```

- #### min
  ```python
  np.min(a)
  np.argmin(a)
  a.min()
  ```

- #### std (standard deviation)
  ```python
  np.std(a)
  a.std()
  ```

- #### mean
  ```python
  np.mean(a)
  a.mean()
  ```

- #### percentile
  ```python
  np.percentile(a, 0 to 100, axis=...)
  ```

  <img src="https://quera.org/qbox/view/sfVrSgbDvL/sum.gif" alt="...">

In [45]:
heights = np.array([[194, 185, 183, 184, 178, 178, 190, 187, 187, 179, 186], 
                    [192, 173, 194, 184, 170, 189, 170, 170, 176, 173, 185]])
print('Iran vs Spain')
print('Mean height:', heights.mean(axis=1))
print('Standard deviation:', heights.std(axis=1))
print("------------------")
new_heights = heights.T
print('Iran vs Spain')
print('Mean height:', new_heights.mean(axis=0))
print('Standard deviation:', new_heights.std(axis=0))

Iran vs Spain
Mean height: [184.63636364 179.63636364]
Standard deviation: [4.79152144 8.91650897]
------------------
Iran vs Spain
Mean height: [184.63636364 179.63636364]
Standard deviation: [4.79152144 8.91650897]


In [46]:
print('Min:', np.min(heights, axis=1)) 
print('25th percentile:', np.percentile(heights, 25, axis=1)) 
print('Median:', np.median(heights, axis=1))
print('75th percentile:', np.percentile(heights, 75, axis=1))
print('Max:', np.max(heights, axis=1))

Min: [178 170]
25th percentile: [181.  171.5]
Median: [185. 176.]
75th percentile: [187. 187.]
Max: [194 194]


## BroadCasting

```Python

a = np.array([
    [3, 5, -4],
    [1, 4, 2],
    [10, 0, 3]
])

a * 2
```

<img src="https://quera.org/qbox/view/bwy2GQBjAt/ufunc.gif" alt="...">

```Python
a = np.array([
    [3, 5, -4],
    [1, 4, 2],
    [10, 0, 3]
])

b = np.array([
    [3, 1, 5]
])

a - 2
```

<img src="https://quera.org/qbox/view/2NggXfAdmV/ufunc2.gif" alt="...">

In [47]:
temp = np.array([[10, 12, 11, 17, 15, 11, 14],
             [13, 15, 18, 21, 19, 18, 17],
             [18, 20, 21, 19, 23, 24, 22],
             [20, 23, 19, 21, 25, 22, 21]])
temp > 10

array([[False,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True]])

In [48]:
print("Number of Days with temperature:", np.count_nonzero(temp > 20))
print("Is any day temp higher than 100: ",np.any(temp>100))
print("Is every day temp higher than 9:", np.all(temp>9))

Number of Days with temperature: 10
Is any day temp higher than 100:  False
Is every day temp higher than 9: True


In [49]:
condition = (temp >= 15) & (temp <= 20)
print(condition)
temp[condition]

[[False False False  True  True False False]
 [False  True  True False  True  True  True]
 [ True  True False  True False False False]
 [ True False  True False False False False]]


array([17, 15, 15, 18, 19, 18, 17, 18, 20, 19, 20, 19])

In [50]:
print('Mean Temperature Of days with temp higher than 20:', temp[temp > 20].mean())
print('Median Temperature of days with temp higher than 20:', np.median(temp[(temp > 15) & (temp < 20)]))

Mean Temperature Of days with temp higher than 20: 22.3
Median Temperature of days with temp higher than 20: 18.0


In [51]:
calendar = np.arange(4*7).reshape(4, 7)
holidays = (calendar%7 >= 5)
first_mid = (calendar < 2*7)
print('Median Temperature of holidays:', np.median(temp[holidays]))
print('Median Temperature fo first 2 weeks:', np.median(temp[first_mid]))
print('Median Temperature of holidays in third and fourth weeks:', np.mean(temp[~first_mid & holidays]))

Median Temperature of holidays: 19.5
Median Temperature fo first 2 weeks: 15.0
Median Temperature of holidays in third and fourth weeks: 22.25


<img src="https://quera.org/qbox/view/Wc4NcDdn8s/fancy%20indexing.gif" alt="...">

```python
a = np.arange(12).reshape(4, 3)
print(a)
row = np.array([0, 2, 3, 2])
col = np.array([0, 2, 1, 0])
a[row, col]
```

In [52]:
a = np.arange(12).reshape(4, 3)
print(a)
row = np.array([0, 2, 3, 2])
col = np.array([0, 2, 1, 0])
a[row, col]

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


array([ 0,  8, 10,  6])

In [53]:
a = np.arange(12)
ind = np.array([[2, 3],
               [4, 1]])
a[ind]

array([[2, 3],
       [4, 1]])

In [54]:
a = np.arange(12).reshape((4,3))
row = np.array([0, 2, 3, 2])
col = np.array([0, 2, 1, 0])
print(row)
print(row.reshape((4,1)))
a[row[:, np.newaxis], col] # row[:,np.newaxis] ==> row.reshape(4,1)


[0 2 3 2]
[[0]
 [2]
 [3]
 [2]]


array([[ 0,  2,  1,  0],
       [ 6,  8,  7,  6],
       [ 9, 11, 10,  9],
       [ 6,  8,  7,  6]])

### at

- no matter how many time you call an index the change will happen only once!
  ```Python
  a = np.array([2, 1, 3, 4, 5])
  a[[1, 1, 2, 4]] *= 10
  print(a)
  ```

- with **at** every time you call an index the change will happen to it!
  ```Python
  a = np.array([2, 1, 3, 4, 5])
  np.add.at(a, [0, 0, 0, 1, 1, 2], 5)
  print(a)
  ```

In [55]:
a = np.array([2,4,5,1])
a[[1,2,3,3,3,3,3,3]]*=10
np.multiply.at(a,[2,3,3,3,3,3],10)
a

array([      2,      40,     500, 1000000])

In [56]:
a = np.array([4 ,9,7,7 ,2 ,10,4,2 ,7 ,5])
print(a)
print(np.partition(a,1))

[ 4  9  7  7  2 10  4  2  7  5]
[ 2  2  7  7  4 10  4  9  7  5]


In [57]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
print('x =', x)
print('y =', y)
np.dot(x,y)

x = [1 2 3]
y = [4 5 6]


32

In [58]:
a = np.random.randint(0,11,(3,4))
b = np.random.randint(0,11,(4,3))
print('a =\n',a)
print('--------')
print('b =\n',b)
np.matmul(a,b)

a =
 [[8 4 9 5]
 [7 7 8 5]
 [8 8 2 7]]
--------
b =
 [[ 8  4  3]
 [ 2  5  5]
 [ 3 10  7]
 [ 2  2  9]]


array([[109, 152, 152],
       [104, 153, 157],
       [100, 106, 141]])

In [59]:
from numpy.linalg import inv, det
a = np.random.randn(4, 4)
print('a =\n',a,'\n')
print('inv =\n',inv(a),'\n')
print('det =\n',det(a),'\n')

a =
 [[-1.23433408 -1.64205635  0.96582374  0.35720084]
 [-0.20323711  0.67498439  0.53068945  0.10756968]
 [ 1.54111155 -0.99699939 -0.29282806 -0.82640276]
 [-1.29294018 -1.15561578 -0.39335448  2.01094439]] 

inv =
 [[-0.27137914  1.23819478  0.88471653  0.34554751]
 [-0.28215805  0.33505809 -0.236244   -0.06488876]
 [ 0.31085649  1.66592095  0.53048173  0.07367224]
 [-0.27582389  1.31451058  0.53683515  0.69657077]] 

det =
 -3.536349736541204 

