# Numpy

- Numpy is Numerical Python !
  
- As you can see the python list save objects inside itself but the numpy array and all its belongings are whole an object!

    <img src="https://devopedia.org/images/article/251/4000.1588007216.png" alt="..." style="width:700px;"/>


In [2]:
import numpy as np

In [3]:
my_array = np.array([1,2,3])

In [4]:
type(my_array)

numpy.ndarray

In [5]:
my_array.ndim

1

In [6]:
my_array.shape

(3,)

In [7]:
print(my_array)
print('each item:', my_array.itemsize, 'bytes')
print('total:',my_array.nbytes, 'bytes')

[1 2 3]
each item: 8 bytes
total: 24 bytes


In [8]:
my_array = np.array([
    [1,2],
    [3,4],
    [5,6]
])

In [9]:
my_array.ndim

2

In [10]:
my_array.shape

(3, 2)

In [11]:
my_array = np.array(12)
my_array.ndim

0

In [12]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
np.ones((3,5,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [15]:
np.full((5,6), fill_value='#')

array([['#', '#', '#', '#', '#', '#'],
       ['#', '#', '#', '#', '#', '#'],
       ['#', '#', '#', '#', '#', '#'],
       ['#', '#', '#', '#', '#', '#'],
       ['#', '#', '#', '#', '#', '#']], dtype='<U1')

In [16]:
np.arange(23, 455,6)

array([ 23,  29,  35,  41,  47,  53,  59,  65,  71,  77,  83,  89,  95,
       101, 107, 113, 119, 125, 131, 137, 143, 149, 155, 161, 167, 173,
       179, 185, 191, 197, 203, 209, 215, 221, 227, 233, 239, 245, 251,
       257, 263, 269, 275, 281, 287, 293, 299, 305, 311, 317, 323, 329,
       335, 341, 347, 353, 359, 365, 371, 377, 383, 389, 395, 401, 407,
       413, 419, 425, 431, 437, 443, 449])

In [17]:
np.arange(0, 10,2, dtype=np.uint8)

array([0, 2, 4, 6, 8], dtype=uint8)

In [18]:
np.linspace(0,155,3)

array([  0. ,  77.5, 155. ])

In [19]:
np.linspace(0,155,3, dtype=np.uint8)

array([  0,  77, 155], dtype=uint8)

In [20]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [21]:
np.empty((3,5), dtype=np.bool_)

array([[ True,  True,  True,  True,  True],
       [ True, False, False, False, False],
       [False, False, False, False, False]])

In [22]:
hello = np.array(['h','e','l','l','o'])
print('each item:', hello.itemsize, 'bytes')
print('total:',hello.nbytes, 'bytes')

each item: 4 bytes
total: 20 bytes


In [23]:
np.random.random(size=(4,3))

array([[0.23417515, 0.09444167, 0.68272597],
       [0.41746921, 0.88996073, 0.90367072],
       [0.78635401, 0.05733398, 0.06378736],
       [0.92798416, 0.62348901, 0.57420205]])

In [26]:
np.random.randint(10,20,(2,4,5), dtype=np.uint8)

array([[[19, 12, 17, 12, 14],
        [11, 10, 11, 16, 13],
        [13, 11, 10, 13, 17],
        [11, 12, 13, 16, 18]],

       [[13, 17, 10, 10, 10],
        [18, 17, 17, 13, 12],
        [13, 17, 15, 13, 15],
        [11, 12, 17, 16, 11]]], dtype=uint8)

In [27]:
np.random.normal(10,20,(3,4,2))

array([[[  6.3394657 ,  34.258247  ],
        [  0.48793442,  -1.21150783],
        [ 21.48777627,  33.74300514],
        [ 18.17528575,   1.48676035]],

       [[  7.85419705,  12.63883171],
        [ 21.80630882, -15.97385448],
        [ 30.07830208,  31.64208101],
        [-33.74750452,  -3.41382872]],

       [[ 12.39685308,  42.58907869],
        [  9.8677703 ,  16.98644078],
        [ 13.11210429,  33.97689383],
        [ -1.83636934,  25.54839915]]])

In [44]:
my_array = np.random.randint(0,10,(2,4,3))
my_array

array([[[6, 6, 7],
        [1, 5, 0],
        [0, 3, 6],
        [4, 8, 9]],

       [[6, 0, 3],
        [9, 5, 1],
        [6, 6, 1],
        [8, 4, 8]]])

In [34]:
np.full_like(my_array, 3)

array([[[3, 3, 3],
        [3, 3, 3],
        [3, 3, 3],
        [3, 3, 3]],

       [[3, 3, 3],
        [3, 3, 3],
        [3, 3, 3],
        [3, 3, 3]]])

In [46]:
my_array[1,1,2]

1

In [49]:
a = np.array([[0, 1, 2],
              [3, 4, 5],
              [6, 7, 8]])
print('a:\n', a)
sub_a = a[1:3, 1:]
print('sub a:\n',sub_a)
sub_a[0, 0] = 10
print('sub a:\n', sub_a)
print('a:\n',a)

a:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
sub a:
 [[4 5]
 [7 8]]
sub a:
 [[10  5]
 [ 7  8]]
a:
 [[ 0  1  2]
 [ 3 10  5]
 [ 6  7  8]]


In [50]:
a = np.array([[0, 1, 2],
              [3, 4, 5],
              [6, 7, 8]])
print("a:\n", a)
sub_copy_a = a[2:4, 1:].copy()
print("sub a:\n", sub_copy_a)
sub_copy_a[0, 0] = 10
print("sub a:\n", sub_copy_a)
print(a)

a:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
sub a:
 [[7 8]]
sub a:
 [[10  8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [57]:
before = np.linspace(0,29,16,dtype=np.uint8)
print("Before:\n", before)
after = before.reshape(4,4)
print("After:\n", after)


Before:
 [ 0  1  3  5  7  9 11 13 15 17 19 21 23 25 27 29]
After:
 [[ 0  1  3  5]
 [ 7  9 11 13]
 [15 17 19 21]
 [23 25 27 29]]


In [61]:
before = np.arange(1,10)
print("Before:\n", before)
after = before.reshape(3,3)
print("After:\n", after)

Before:
 [1 2 3 4 5 6 7 8 9]
After:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [67]:
before = np.arange(30)
print("Before:\n", before)
after = before.reshape(2,5,-1)
print("After:\n", after)

Before:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
After:
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]]


In [71]:
before = np.random.randint(low=0,high=2,size=(2,4,3))
print("Before:\n", before)
after = before.reshape(-1)
print("After:\n", after)

Before:
 [[[1 1 0]
  [1 1 1]
  [1 0 1]
  [1 1 1]]

 [[0 0 1]
  [0 1 0]
  [0 0 1]
  [1 1 1]]]
After:
 [1 1 0 1 1 1 1 0 1 1 1 1 0 0 1 0 1 0 0 0 1 1 1 1]


In [74]:

a = np.array([[0, 1, 2],
             [3, 4, 5],
             [6, 7, 8],
             [9, 10, 11]])
print(a.size)
print(a.shape)
print(a.ndim)
print(a[:2, 1:2])
print(a[:2, 1])

12
(4, 3)
2
[[1]
 [4]]
[1 4]
