# Numpy

- Numpy is Numerical Python !
  
- As you can see the python list save objects inside itself but the numpy array and all its belongings are whole an object!

    <img src="https://devopedia.org/images/article/251/4000.1588007216.png" alt="..." style="width:700px;"/>

- Dimensions in numpy arrays:
    
    <img src="https://nustat.github.io/DataScience_Intro_python/Datasets/numpy_image.png" alt="..." style="width:700px;">


In [2]:
import numpy as np

In [2]:
my_array = np.array([1,2,3])

In [3]:
type(my_array)

numpy.ndarray

In [4]:
my_array.ndim

1

In [5]:
my_array.shape

(3,)

In [6]:
print(my_array)
print('each item:', my_array.itemsize, 'bytes')
print('total:',my_array.nbytes, 'bytes')

[1 2 3]
each item: 8 bytes
total: 24 bytes


In [7]:
my_array = np.array([
    [1,2],
    [3,4],
    [5,6]
])

In [8]:
my_array.ndim

2

In [9]:
my_array.shape

(3, 2)

In [10]:
my_array = np.array(12)
my_array.ndim

0

In [11]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
np.ones((3,5,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [14]:
np.full((5,6), fill_value='#')

array([['#', '#', '#', '#', '#', '#'],
       ['#', '#', '#', '#', '#', '#'],
       ['#', '#', '#', '#', '#', '#'],
       ['#', '#', '#', '#', '#', '#'],
       ['#', '#', '#', '#', '#', '#']], dtype='<U1')

In [15]:
np.arange(23, 455,6)

array([ 23,  29,  35,  41,  47,  53,  59,  65,  71,  77,  83,  89,  95,
       101, 107, 113, 119, 125, 131, 137, 143, 149, 155, 161, 167, 173,
       179, 185, 191, 197, 203, 209, 215, 221, 227, 233, 239, 245, 251,
       257, 263, 269, 275, 281, 287, 293, 299, 305, 311, 317, 323, 329,
       335, 341, 347, 353, 359, 365, 371, 377, 383, 389, 395, 401, 407,
       413, 419, 425, 431, 437, 443, 449])

In [16]:
np.arange(0, 10,2, dtype=np.uint8)

array([0, 2, 4, 6, 8], dtype=uint8)

In [17]:
np.linspace(0,155,3)

array([  0. ,  77.5, 155. ])

In [18]:
np.linspace(0,155,3, dtype=np.uint8)

array([  0,  77, 155], dtype=uint8)

In [19]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [20]:
np.empty((3,5), dtype=np.bool_)

array([[ True,  True,  True,  True,  True],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [21]:
hello = np.array(['h','e','l','l','o'])
print('each item:', hello.itemsize, 'bytes')
print('total:',hello.nbytes, 'bytes')

each item: 4 bytes
total: 20 bytes


In [22]:
np.random.random(size=(4,3))

array([[0.80785575, 0.92041256, 0.67416398],
       [0.62903168, 0.97738851, 0.30424134],
       [0.92768861, 0.05304542, 0.36467473],
       [0.22143617, 0.5244219 , 0.45664267]])

In [23]:
np.random.randint(10,20,(2,4,5), dtype=np.uint8)

array([[[14, 14, 12, 13, 13],
        [13, 17, 14, 13, 10],
        [14, 15, 17, 16, 13],
        [10, 16, 14, 13, 14]],

       [[16, 13, 19, 10, 13],
        [18, 18, 12, 15, 11],
        [10, 15, 11, 18, 11],
        [13, 15, 11, 12, 13]]], dtype=uint8)

In [24]:
np.random.normal(10,20,(3,4,2))

array([[[  6.91724044,  30.60603833],
        [-11.45485556,  -1.87437116],
        [ 51.06110745,  40.73824532],
        [ 22.60496762,  31.18595592]],

       [[-12.72174091,  14.76509374],
        [ 16.92633459,  14.60919513],
        [ -5.46091128,  -6.88332456],
        [-22.81521041,  14.52245678]],

       [[ -2.59748117,  55.39409837],
        [  7.22207971,  -2.37797262],
        [ -1.50777056,   0.10356204],
        [ 33.2545539 ,  -8.29024619]]])

In [25]:
my_array = np.random.randint(0,10,(2,4,3))
my_array

array([[[2, 5, 3],
        [3, 8, 2],
        [2, 4, 7],
        [3, 8, 5]],

       [[8, 8, 8],
        [3, 3, 1],
        [2, 6, 3],
        [8, 7, 2]]])

In [26]:
np.full_like(my_array, 3)

array([[[3, 3, 3],
        [3, 3, 3],
        [3, 3, 3],
        [3, 3, 3]],

       [[3, 3, 3],
        [3, 3, 3],
        [3, 3, 3],
        [3, 3, 3]]])

In [27]:
my_array[1,1,2]

1

In [28]:
a = np.array([[0, 1, 2],
              [3, 4, 5],
              [6, 7, 8]])
print('a:\n', a)
sub_a = a[1:3, 1:]
print('sub a:\n',sub_a)
sub_a[0, 0] = 10
print('sub a:\n', sub_a)
print('a:\n',a)

a:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
sub a:
 [[4 5]
 [7 8]]
sub a:
 [[10  5]
 [ 7  8]]
a:
 [[ 0  1  2]
 [ 3 10  5]
 [ 6  7  8]]


In [29]:
a = np.array([[0, 1, 2],
              [3, 4, 5],
              [6, 7, 8]])
print("a:\n", a)
sub_copy_a = a[2:4, 1:].copy()
print("sub a:\n", sub_copy_a)
sub_copy_a[0, 0] = 10
print("sub a:\n", sub_copy_a)
print(a)

a:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
sub a:
 [[7 8]]
sub a:
 [[10  8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [30]:
before = np.linspace(0,29,16,dtype=np.uint8)
print("Before:\n", before)
after = before.reshape(4,4)
print("After:\n", after)


Before:
 [ 0  1  3  5  7  9 11 13 15 17 19 21 23 25 27 29]
After:
 [[ 0  1  3  5]
 [ 7  9 11 13]
 [15 17 19 21]
 [23 25 27 29]]


In [31]:
before = np.arange(1,10)
print("Before:\n", before)
after = before.reshape(3,3)
print("After:\n", after)

Before:
 [1 2 3 4 5 6 7 8 9]
After:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [32]:
before = np.arange(30)
print("Before:\n", before)
after = before.reshape(2,5,-1)
print("After:\n", after)

Before:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
After:
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]]


In [33]:
before = np.random.randint(low=0,high=2,size=(2,4,3))
print("Before:\n", before)
after = before.reshape(-1)
print("After:\n", after)

Before:
 [[[0 0 1]
  [0 1 1]
  [1 1 1]
  [0 0 1]]

 [[1 0 1]
  [1 0 1]
  [0 1 0]
  [0 1 1]]]
After:
 [0 0 1 0 1 1 1 1 1 0 0 1 1 0 1 1 0 1 0 1 0 0 1 1]


In [34]:

a = np.array([[0, 1, 2],
             [3, 4, 5],
             [6, 7, 8],
             [9, 10, 11]])
print(a.size)
print(a.shape)
print(a.ndim)
print(a[:2, 1:2])
print(a[:2, 1])

12
(4, 3)
2
[[1]
 [4]]
[1 4]


## Transpose
<img src="https://quera.org/qbox/view/xfWkJ9uk6z/transpose.gif" alt="...">

In [35]:
a = np.arange(6).reshape(2,3)
print(a,'\n')
print(a.T,'\n')
print(np.transpose(a),'\n')

[[0 1 2]
 [3 4 5]] 

[[0 3]
 [1 4]
 [2 5]] 

[[0 3]
 [1 4]
 [2 5]] 



In [36]:
a = np.arange(24).reshape(2, 3, 4)
print(a,'\n-----------')
print(a.transpose(1,2,0))

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]] 
-----------
[[[ 0 12]
  [ 1 13]
  [ 2 14]
  [ 3 15]]

 [[ 4 16]
  [ 5 17]
  [ 6 18]
  [ 7 19]]

 [[ 8 20]
  [ 9 21]
  [10 22]
  [11 23]]]


In [37]:
a = np.arange(24).reshape(3,4,2)
print(a,'\n-------')
print(a.swapaxes(0,1)) # zero dimension which is 3 / first dimension which is 4

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]] 
-------
[[[ 0  1]
  [ 8  9]
  [16 17]]

 [[ 2  3]
  [10 11]
  [18 19]]

 [[ 4  5]
  [12 13]
  [20 21]]

 [[ 6  7]
  [14 15]
  [22 23]]]


In [38]:
a = np.arange(24).reshape(3,4,2)
print(a)
print('-----------')
b = a.swapaxes(0,2)
print(b)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]]
-----------
[[[ 0  8 16]
  [ 2 10 18]
  [ 4 12 20]
  [ 6 14 22]]

 [[ 1  9 17]
  [ 3 11 19]
  [ 5 13 21]
  [ 7 15 23]]]


## Concatenate
<img src="https://quera.org/qbox/view/Yw0nPkHTuR/concatenate.gif">

In [39]:
a = np.arange(6).reshape(2,3)
b = np.arange(7,13).reshape(2,3)
print(np.concatenate((a,b)))
print("----------")
print(np.concatenate((a,b), axis=None))
print("----------")
print(np.concatenate((a,b), axis=1))
print("----------")
print(np.concatenate((a,b), axis=0))


[[ 0  1  2]
 [ 3  4  5]
 [ 7  8  9]
 [10 11 12]]
----------
[ 0  1  2  3  4  5  7  8  9 10 11 12]
----------
[[ 0  1  2  7  8  9]
 [ 3  4  5 10 11 12]]
----------
[[ 0  1  2]
 [ 3  4  5]
 [ 7  8  9]
 [10 11 12]]


## Split

<img src="https://quera.org/qbox/view/SHhG2Vh91J/split.png" alt="..." style="width:800px;">

In [40]:
a = np.arange(1,21)
np.split(a, [5,10,15])

[array([1, 2, 3, 4, 5]),
 array([ 6,  7,  8,  9, 10]),
 array([11, 12, 13, 14, 15]),
 array([16, 17, 18, 19, 20])]

In [41]:
a = np.arange(24).reshape(4,6)
b,c = np.split(a,2,axis=0)
d,e,f = np.split(a,3,axis=1)
print(b,'\n---------\n',c,'\n---------')
print(d,'\n---------\n',e,'\n---------\n',f)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]] 
---------
 [[12 13 14 15 16 17]
 [18 19 20 21 22 23]] 
---------
[[ 0  1]
 [ 6  7]
 [12 13]
 [18 19]] 
---------
 [[ 2  3]
 [ 8  9]
 [14 15]
 [20 21]] 
---------
 [[ 4  5]
 [10 11]
 [16 17]
 [22 23]]


In [42]:
a = np.random.randint(0, 10, (3,4))
b = np.random.randint(0, 10, (3,4)) 
print('a :\n', a)
print('b :\n', b)

def cal_sum(a, b) :
    output = np.empty(a.shape, dtype='int_')
    for i in range(len(a)):
        output[i] = a[i] + b[i]
    return output
print("SUM:")
print(cal_sum(a, b))

a :
 [[0 3 5 3]
 [4 8 6 7]
 [4 8 0 0]]
b :
 [[2 2 2 4]
 [9 5 1 6]
 [1 1 5 4]]
SUM:
[[ 2  5  7  7]
 [13 13  7 13]
 [ 5  9  5  4]]


## Binary Universal Functions

- #### add
  ```python
  np.add(a,b)
  ```
- #### subtract
    ```python
  np.subtract(a,b)
  ```
- #### multiply
    ```python
  np.multiply(a,b)
  ```
- #### divide
    ```python
  np.divide(a,b)
  ```

In [43]:
a = np.random.randint(0,11,(4,5))
b = np.random.randint(1,11,(4,5))
 
print(a)
print()
print(b)
print()
print(np.add(a,b),'\n--------------')
print(np.subtract(a,b),'\n------------')
print(np.multiply(a,b),'\n------------')
print(np.divide(a,b,dtype=np.float16))


[[ 5  4  9  5  8]
 [ 1 10  3  8  0]
 [ 8  1  9  3  2]
 [ 3  5  7  8  4]]

[[ 1 10  4  3  5]
 [ 8  3  1  8  3]
 [10  8 10  4  1]
 [ 1 10  4  9  5]]

[[ 6 14 13  8 13]
 [ 9 13  4 16  3]
 [18  9 19  7  3]
 [ 4 15 11 17  9]] 
--------------
[[ 4 -6  5  2  3]
 [-7  7  2  0 -3]
 [-2 -7 -1 -1  1]
 [ 2 -5  3 -1 -1]] 
------------
[[ 5 40 36 15 40]
 [ 8 30  3 64  0]
 [80  8 90 12  2]
 [ 3 50 28 72 20]] 
------------
[[5.     0.4    2.25   1.667  1.6   ]
 [0.125  3.334  3.     1.     0.    ]
 [0.8    0.125  0.9    0.75   2.    ]
 [3.     0.5    1.75   0.8887 0.8   ]]


## Unary Universal Functions

- #### abs
  ```python
  np.abs(a)
  ```
- #### sqrt
    ```python
  np.sqrt(a)
  ```
- #### square
    ```python
  np.square(a)
  ```
- #### isnan
    ```python
  np.isnan(a)
  ```

In [2]:
a = np.random.randint(-10,10,(3,3))
print(a)
print()
print(np.square(a),'\n--------------')
print(np.abs(a),'\n------------')
print(np.isnan(a),'\n------------')
np.seterr(invalid="ignore")
print(np.sqrt(a,dtype=np.float16))

[[  2   9   6]
 [ -3   3   4]
 [ -4  -3 -10]]

[[  4  81  36]
 [  9   9  16]
 [ 16   9 100]] 
--------------
[[ 2  9  6]
 [ 3  3  4]
 [ 4  3 10]] 
------------
[[False False False]
 [False False False]
 [False False False]] 
------------
[[1.414 3.    2.45 ]
 [  nan 1.732 2.   ]
 [  nan   nan   nan]]


## Aggregation Functions

- #### sum
  ```python
  np.sum(a)

  a.sum()
  ```
- #### max
  ```python
  np.max(a)

  a.max()
  ```
- #### min
  ```python
  np.min(a)

  a.min()
  ```
- #### std (standard deviation)
  ```python
  np.std(a)

  a.std()
  ```

- #### mean
  ```python
  np.mean(a)

  a.mean()
  ```

- #### percentile
  ```python
  np.percentile(a, 0 to 100, axis=...)

  ```

  <img src="https://quera.org/qbox/view/sfVrSgbDvL/sum.gif" alt="...">

In [10]:
heights = np.array([[194, 185, 183, 184, 178, 178, 190, 187, 187, 179, 186], 
                    [192, 173, 194, 184, 170, 189, 170, 170, 176, 173, 185]])
print('Iran vs Spain')
print('Mean height:', heights.mean(axis=1))
print('Standard deviation:', heights.std(axis=1))
print("------------------")
new_heights = heights.T
print('Iran vs Spain')
print('Mean height:', new_heights.mean(axis=0))
print('Standard deviation:', new_heights.std(axis=0))

Iran vs Spain
Mean height: [184.63636364 179.63636364]
Standard deviation: [4.79152144 8.91650897]
------------------
Iran vs Spain
Mean height: [184.63636364 179.63636364]
Standard deviation: [4.79152144 8.91650897]


In [11]:
print('Min:', np.min(heights, axis=1)) 
print('25th percentile:', np.percentile(heights, 25, axis=1)) 
print('Median:', np.median(heights, axis=1))
print('75th percentile:', np.percentile(heights, 75, axis=1))
print('Max:', np.max(heights, axis=1))

Min: [178 170]
25th percentile: [181.  171.5]
Median: [185. 176.]
75th percentile: [187. 187.]
Max: [194 194]
